version: '2'
services:
  cityresidencestrack:
    image: cityresidencestrack
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_PROFILES_ACTIVE=prod,swagger'
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://cityresidencestrack-postgresql:5432/CityResidencesTrack'
      - JHIPSTER_SLEEP=10
    ports:
      - '8080:8080'
  cityresidencestrack-postgresql:
    image: 'postgres:12.3'
    environment:
      - POSTGRES_USER=CityResidencesTrack
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
