version: '2'
services:
  cityresidencestrack-app:
    image: cityresidencestrack
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://cityresidencestrack-postgresql:5432/CityResidencesTrack
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  cityresidencestrack-postgresql:
    extends:
      file: postgresql.yml
      service: cityresidencestrack-postgresql
